name: maifs-trufor
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - albumentations=1.2.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.0
  - cloudpickle=2.1.0
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - cython=0.29.28
  - cytoolz=0.11.0
  - dask-core=2022.2.0
  - dbus=1.13.6
  - decorator=5.1.1
  - expat=2.4.1
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - freetype=2.11.0
  - fsspec=2022.7.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.68.3
  - glib-tools=2.68.3
  - gmp=6.2.1
  - gnutls=3.6.15
  - graphite2=1.3.13
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - harfbuzz=2.8.2
  - hdf5=1.10.6
  - icu=68.1
  - idna=3.3
  - imageio=2.21.1
  - intel-openmp=2021.4.0
  - jasper=1.900.1
  - joblib=1.1.0
  - jpeg=9e
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.3
  - libgomp=9.3.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libopencv=4.4.0
  - libpng=1.6.37
  - libpq=13.3
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - locket=1.0.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - ncurses=6.3
  - nettle=3.7.3
  - networkx=2.5
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nspr=4.30
  - nss=3.67
  - numpy=1.21.5
  - numpy-base=1.21.5
  - opencv=4.4.0
  - openh264=2.1.1
  - openssl=1.1.1w
  - packaging=21.3
  - partd=1.3.0
  - pcre=8.45
  - pillow=9.0.1
  - pip=21.2.2
  - pixman=0.40.0
  - pthread-stubs=0.4
  - py-opencv=4.4.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.7.13
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - pywavelets=1.1.1
  - qt=5.12.9
  - qudida=0.0.4
  - readline=8.1.2
  - scikit-image=0.16.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.3
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - toolz=0.12.0
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tornado=6.1
  - urllib3=1.26.9
  - wheel=0.37.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
      - absl-py==1.1.0
      - addict==2.4.0
      - cachetools==5.2.0
      - charset-normalizer==2.0.12
      - click==7.1.2
      - colorama==0.4.5
      - dataclasses==0.6
      - fonttools==4.33.3
      - future==0.18.2
      - google-auth==2.8.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.46.3
      - importlib-metadata==4.11.4
      - jpegio==0.2.4
      - kiwisolver==1.4.2
      - markdown==3.3.7
      - markupsafe==2.1.5
      - matplotlib==3.5.2
      - mmcls==0.23.1
      - mmcv-full==1.5.3
      - mmsegmentation==0.25.0
      - model-index==0.1.11
      - oauthlib==3.2.0
      - opencv-python==4.5.5.64
      - openmim==0.1.6
      - ordered-set==4.1.0
      - pandas==1.3.5
      - platformdirs==4.0.0
      - prettytable==3.3.0
      - protobuf==3.19.4
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pytz==2022.1
      - pyyaml==6.0
      - requests==2.28.0
      - requests-oauthlib==1.3.1
      - rsa==4.8
      - seaborn==0.11.2
      - tabulate==0.8.10
      - tensorboard==2.9.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.5.1
      - timm==0.5.4
      - tomli==2.0.1
      - torch-dct==0.1.5
      - torchsummary==1.5.1
      - tqdm==4.64.0
      - typing-extensions==4.7.1
      - wcwidth==0.2.14
      - werkzeug==2.2.3
      - yacs==0.1.8
      - yapf==0.43.0
      - zipp==3.15.0
