name: maifs-mvss
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2025.12.2
  - certifi=2021.5.30
  - cudatoolkit=10.1.243
  - freetype=2.13.3
  - giflib=5.2.2
  - icu=73.1
  - intel-openmp=2025.0.0
  - jpeg=9f
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.3
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libpng=1.6.50
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.5.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mkl=2025.0.0
  - ncurses=6.5
  - ninja=1.13.1
  - ninja-base=1.13.1
  - olefile=0.46
  - openssl=1.1.1w
  - pip=21.2.2
  - pthread-stubs=0.3
  - python=3.6.13
  - pytorch=1.5.1
  - readline=8.3
  - setuptools=58.0.4
  - sqlite=3.51.1
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - torchvision=0.6.1
  - wheel=0.37.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - albumentations==0.4.6
      - cycler==0.11.0
      - decorator==4.4.2
      - docutils==0.15.2
      - future==1.0.0
      - imageio==2.15.0
      - imgaug==0.4.0
      - kiwisolver==1.3.1
      - matplotlib==3.0.3
      - networkx==2.5.1
      - numpy==1.19.4
      - opencv-python==4.1.2.30
      - pillow==8.4.0
      - protobuf==3.19.6
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pywavelets==1.1.1
      - pyyaml==5.3.1
      - scikit-image==0.17.2
      - scipy==1.5.4
      - shapely==1.8.5.post1
      - six==1.17.0
      - tensorboardx==2.1
      - tifffile==2020.9.3
      - timm==0.3.1
      - tqdm==4.45.0
