name: maifs-catnet
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2025.12.2
  - certifi=2021.5.30
  - cffi=1.14.6
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - freetype=2.13.3
  - giflib=5.2.2
  - intel-openmp=2025.0.0
  - jpeg=9f
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.3
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libpng=1.6.50
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.5.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.5
  - ninja=1.13.1
  - ninja-base=1.13.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1w
  - pillow=8.3.1
  - pip=21.2.2
  - pthread-stubs=0.3
  - pycparser=2.21
  - python=3.6.13
  - readline=8.3
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.37.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - cycler==0.11.0
      - cython==3.0.12
      - future==1.0.0
      - importlib-resources==5.4.0
      - jpegio==0.2.4
      - kiwisolver==1.3.1
      - matplotlib==3.3.4
      - opencv-python==4.5.5.64
      - packaging==21.3
      - pandas==1.1.5
      - protobuf==4.21.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.1
      - scipy==1.5.4
      - seaborn==0.11.2
      - tensorboardx==2.6.2.2
      - torch==1.6.0+cu101
      - torch-dct==0.1.6
      - torchvision==0.7.0+cu101
      - tqdm==4.64.1
      - yacs==0.1.8
      - zipp==3.6.0
