name: maifs-hinet
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=0.11.0
  - aiohttp=3.7.3
  - async-timeout=3.0.1
  - attrs=20.3.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.8
  - cachetools=4.2.0
  - cairo=1.14.12
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - cryptography=2.9.2
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2020.12.0
  - dbus=1.13.18
  - decorator=4.4.2
  - expat=2.2.10
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.10.4
  - glib=2.66.1
  - google-auth=1.24.0
  - google-auth-oauthlib=0.4.2
  - graphite2=1.3.14
  - grpcio=1.31.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.10
  - imageio=2.9.0
  - importlib-metadata=2.0.0
  - intel-openmp=2020.2
  - jasper=2.0.14
  - jpeg=9b
  - kiwisolver=1.3.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markdown=3.3.3
  - matplotlib=2.2.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - multidict=4.7.6
  - natsort=7.1.0
  - ncurses=6.2
  - networkx=2.5.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.1.0
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1i
  - pandas=1.2.0
  - pcre=8.44
  - pillow=6.0.0
  - pip=20.3.3
  - pixman=0.40.0
  - py-opencv=3.4.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyjwt=2.0.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - pytorch=1.0.1
  - pytz=2020.4
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - readline=8.0
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - scikit-image=0.14.2
  - scikit-learn=0.20.3
  - scipy=1.5.2
  - setuptools=51.0.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - tensorboard=2.3.0
  - tensorboard-plugin-wit=1.6.0
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.54.1
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.2
  - werkzeug=1.0.1
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.5.1
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
      - backcall==0.2.0
      - coloredlogs==15.0
      - et-xmlfile==1.0.1
      - humanfriendly==9.1
      - ipdb==0.13.7
      - ipython==7.22.0
      - ipython-genutils==0.2.0
      - jdcal==1.4.1
      - jedi==0.18.0
      - openpyxl==3.0.5
      - parso==0.8.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - prompt-toolkit==3.0.18
      - protobuf==3.14.0
      - ptyprocess==0.7.0
      - pygments==2.8.1
      - tensorboardx==2.1
      - toml==0.10.2
      - torchsummary==1.5.1
      - torchvision==0.2.2
      - traitlets==5.0.5
      - wcwidth==0.2.5
